### ISSUE TITLE
xarray content not displayed

### ISSUE THREAD

**Issue by niowniow** [opengeos/leafmap#1021]
### Environment Information

-   leafmap version: 0.42.5
-   Operating System: Linux
-   Browser: Firefox, Chromium

I'm not using conda to manage the dependencies, only pypi packages.

### Description

The xarray-based examples on the leafmap website are not showing any content, e.g. the xarray part on [49_split_control](https://leafmap.org/notebooks/49_split_control/). The same issue occurs when running the example in Colab. (JupyterLite and Binder fail for other reasons).

I experience a similar issue when running a marimo notebook plotting a leafmap from within a docker container. Running the notebook without docker container runs it just fine, but from within the docker container it does not work. 

Could there be any dependencies missing which make it silently fail? I wouldn't know where to start debugging, since there are no warning or error messages.

There are no logs

### What I Did
- Look at various xarray examples on the webpage, no content is shown

Relevant [localtileserver](https://github.com/banesullivan/localtileserver/issues/233) issue and [leafmap discussion](https://github.com/opengeos/leafmap/discussions/1011). Note: I understand that this is a localtileserver issue, however, this is mainly about the non-working examples of leafmap.

**Comment by giswqs** [comment]
Try openning the network tab in the Chrome Developer Console and see what errors in the tile URLs.

**Comment by giswqs** [comment]
You also need to install jupyter-server-proxy.

**Comment by giswqs** [comment]
It seems there is a bug with the folium backed. The ipyleaflet backend works fine. 

```python
import leafmap

m = leafmap.Map(center=[37.6, -119], zoom=9)
m.split_map(
    dem_ds,
    dem_class,
    left_args={"layer_name": "DEM", "colormap": "terrain"},
    right_args={"layer_name": "Classified DEM", "colormap": "coolwarm"},
)
m
```
![image](https://github.com/user-attachments/assets/7913f684-2e68-4ad1-bfb5-3944d8787509)

**Comment by niowniow** [comment]
Thanks a lot!

> You also need to install jupyter-server-proxy.

Installing jupyter-server-proxy is not fixing the issue on my side. Maybe because I'm not using jupyter notebooks. 

My main issue is that `add_raster` or related calls, starts a localtileserver on a non-deterministic port on localhost. This port is only accessible in the docker container. I assume `jupyter-server-proxy` would reverse proxy that port.

In my case, if I could set the port explicitly, I would be able to forward the port and it works. I did that by scraping the port from the browsers network tab. However whenever I restart my app, the localtileserver is started on a different port.

Do you know if it's possible to fix the localtileserver port to a specific number in the call to `add_raster`?

**Comment by giswqs** [comment]
The add_raster method has the port parameter for setting the port number 

https://localtileserver.banesullivan.com/api/index.html#localtileserver.get_leaflet_tile_layer
