### ISSUE TITLE
Problem with create_timelapse

### ISSUE THREAD

**Issue by UrielMendoza** [opengeos/leafmap#411]
### Environment Information

-   leafmap version: 0.18.10
-   Python version: 3.10.10
-   Operating System: Windows 11

### Description

I get this message when i try to run the function ```create_timelapse()``` it only reads the images but doesn't create any .gif files.

![image](https://user-images.githubusercontent.com/46738566/230522171-0a9d9217-7070-4dea-ae5d-e4be246d0ef0.png)

And when i try to run in the test_leafmap.py, i have this error.
`'numpy.ndarray' object has no attribute 'interp'`

### What I Did
I have this collab with the code that download the images that i want to make the animation.

https://colab.research.google.com/drive/13GidiQw83N1dOztVO6V9BudDNevhWCin?usp=sharing

```
images = '/content/landsat08_izt/*.tif'
leafmap.create_timelapse(
    images,
    out_gif='/content/landsat08_izt.gif',
    bands=[0, 1, 2],
    fps=10,
    progress_bar_color='blue',
    add_text=True,
    text_xy=('3%', '3%'),
    text_sequence=1984,
    font_size=20,
    font_color='black',
    mp4=False,
    reduce_size=False,
    quiet=False,
)
```

**Comment by giswqs** [comment]
If you use geemap, why not just use the geemap.create_timelapse() function directly?

https://book.geemap.org/chapters/09_timelapse.html#creating-timeseries
https://geemap.org/timelapse/#geemap.timelapse.create_timelapse

**Comment by UrielMendoza** [comment]
Yes, thank you very much, the animation works very well 👍 .
i will use geemap for this.

![image](https://user-images.githubusercontent.com/46738566/230531684-83df6e5a-2def-416d-a72a-c514827e8b96.png)
