### ISSUE TITLE
Allow customization of list of STAC catalogs to just one catalog (and that can be the STAC catalog)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [opengeos/leafmap#412]
### Description

Right now, when you use leafmap, the STAC widget includes many catalogs in the "Discover STAC Catalog". I understand all the catalogs are coming from https://github.com/giswqs/geospatial-data-catalogs. It may be necessary able to identify a different github source of the catalogs and even which catalogs to include from that source.

Use case is that we want to build this but only target https://stac.maap-project.org - perhaps other STAC catalogs in the future but that is to be determined.

So the behavior I am looking for is, ideally upon installation of the library you can specify which catalog source to use if it is not https://github.com/giswqs/geospatial-data-catalogs. A simpler solution may be to pass a `catalog_source=` parameter to the leafmap.Map instantiation.

**Comment by giswqs** [comment]
This feature has been implemented. See the notebook example [here](https://github.com/opengeos/leafmap/blob/master/examples/notebooks/73_custom_stac.ipynb).

**Comment by giswqs** [comment]
A demo:

https://user-images.githubusercontent.com/5016453/231044656-145e9689-ff4c-40ee-924e-0e900126d0ed.mp4
