### ISSUE TITLE
Support having just one drop down for single band

### ISSUE THREAD

**Issue by abarciauskas-bgse** [opengeos/leafmap#415]
### Description

Right now, users much select a band for RGB values. Many geotiffs are not produced from optical imagery so bands do not represent RGB bands. I'm not sure the best way to make this configurable yet, but opening for discussion. There are at least a couple options for determining the number of bands:

1. Read the number of bands from STAC metadata. Problem with this is, I'm not sure that band information is being represented consistently across STAC collections
2. Read band data from the files themselves. This may be prohibitively slow.

Assuming the bands are not RGB bands, then:

1. If there is one band, then that band should be what is already selected for making the color map
2. If there is greater than one band, the user may want to create some band combination OR the user may want to include different bands as different layers.

I think a comprehensive solution may require more thought, so perhaps for now, we should just have clear communication when loading STAC items, what is possible. 

1. If an item not a geotiff, user should know that no layers can be created (AFAIK)
2. If an item is a COG, users should know they can select the same band for all RGB values

**Comment by abarciauskas-bgse** [comment]
@giswqs I'm still thinking through how band selection should work for items which are do not have RGB bands. Let me know if you have other ideas or questions about this.

**Comment by giswqs** [comment]
This has already been implemented. If the STAC Item has only one or two bands, the visualization option will automatically switch to `1 band (Grayscale)`. See the demo. 


https://user-images.githubusercontent.com/5016453/231231501-9782314e-c6ad-4943-b453-7b1a4702d740.mp4

**Comment by giswqs** [comment]
The automatic switch occurs in 9 seconds of the demo.
