### ISSUE TITLE
In leafmap.tms_to_geotiff(), add JP2000 and ECW formats; also option of coordinate system for output raster. 

### ISSUE THREAD

**Issue by ravishbapna** [opengeos/leafmap#424]
### Description

Describe the feature (e.g., new functions/tutorials) you would like to propose.
Tell us what can be achieved with this new feature and what's the expected outcome.

### Source code

```
Paste your source code here if have sample code to share.
```

**Comment by giswqs** [comment]
I can add support for the JP2000 format, but not the ECW format, which requires a license. You are welcome to install the ECW SDK on your own to deal with ECW format. 
https://gis.stackexchange.com/questions/352064/how-to-work-with-ecw-in-gdal
