### ISSUE TITLE
Enable custom xarray Dataset in `add_raster_legacy`

### ISSUE THREAD

**Issue by julien-blanchon** [opengeos/leafmap#442]
### Description

`leafmap.Map.add_raster_legacy` is taking a image (in image_path in this context) as a path and crash if the path didn't exist.
This prevent the usage of remote (s3, cog ...) image in this context.

This also prevent the usage of custom computed xr.Dataset.

A better approch could be directly take a xr.Dataset object in the `add_raster_legacy` and let the user care about the format.

Eventually raise an error if xarray_leaflet is not installed and loaded by checking that the .leaflet is present on the given Dataset

**Comment by giswqs** [comment]
Good suggestion. Would you like to submit a pull request?
