### ISSUE TITLE
bounds warning in numpy_to_cog

### ISSUE THREAD

**Issue by zxdawn** [opengeos/leafmap#472]
If `bounds` are not passed into `numpy_to_cog`, it will be set as a constant global value.

https://github.com/opengeos/leafmap/blob/cf9d594af2859f4059d449842f1ba4bd2797523d/leafmap/common.py#L3754-L3755

This will lead to the wrong profile in COG file. It's better to raise a warning when it's not passed.

**Comment by giswqs** [comment]
Good suggestion. Would you like to submit a PR to fix it?

**Comment by zxdawn** [comment]
Sure. I will create one ;)
