### ISSUE TITLE
Choropleth map is not working in windows

### ISSUE THREAD

**Issue by jxlyn** [opengeos/leafmap#483]
### Environment Information

-   leafmap version: 0.22.0
-   Python version: 3.9.13
-   Operating System: Windows 11 Enterprise

### Description
I'm trying to do the same example as https://colab.research.google.com/github/opengeos/leafmap/blob/master/examples/notebooks/53_choropleth.ipynb#scrollTo=iyOJ30pLR_ur
however, it shows the type error

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
 in 
      1 m = leafmap.Map()
----> 2 m.add_data(
      3     data, column='POP_EST', scheme='Quantiles', cmap='Blues', legend_title='Population'
      4 )
      5 m

venv\lib\site-packages\leafmap\leafmap.py in add_data(self, data, column, colors, labels, cmap, scheme, k, add_legend, legend_title, legend_position, legend_kwds, classification_kwds, layer_name, style, hover_style, style_callback, info_mode, encoding, **kwargs)
   3687             style_callback = lambda feat: {"fillColor": feat["properties"]["color"]}
   3688 
-> 3689         self.add_gdf(
   3690             gdf,
   3691             layer_name=layer_name,

packages\leafmap\leafmap.py in add_gdf(self, gdf, layer_name, style, hover_style, style_callback, fill_colors, info_mode, zoom_to_layer, encoding, **kwargs)
   2476         """
   2477         for col in gdf.columns:
-> 2478             if gdf[col].dtype in ["datetime64[ns]", "datetime64[ns, UTC]"]:
   2479                 gdf[col] = gdf[col].astype(str)
   2480 

TypeError: Invalid datetime unit in metadata string "[ns, UTC]"



```

**Comment by cladosphaero** [comment]
I am also having this issue

**Comment by giswqs** [comment]
Run `leafmap.update_package()` and restart the kernel

**Comment by jxlyn** [comment]
![Screenshot 2023-06-29 121505](https://github.com/opengeos/leafmap/assets/75590646/838b1dda-8984-47aa-b992-845a4375fde2)

Hi, thank you for solving this issue. I was trying to use the same example in [the tutorial](https://colab.research.google.com/github/opengeos/leafmap/blob/master/examples/notebooks/53_choropleth.ipynb#scrollTo=iyOJ30pLR_ur) again. Is there anyway to remove the print statement when generating the map? Thank you!

**Comment by giswqs** [comment]
Run `leafmap.update_package()` and restart the kernel. The warning message should be gone now.
