### ISSUE TITLE
75_Segment_Anything 

### ISSUE THREAD

**Issue by Niko-La** [opengeos/leafmap#488]
```
device = 'cuda' if torch.cuda.is_available() else 'cpu'
sam = SamGeo(
    checkpoint='/content/sam_vit_h_4b8939.pth',
    model_type='vit_h',
    device=device,
    #erosion_kernel=(3, 3),
    #mask_multiplier=255,
    sam_kwargs=None,
)
```

Golt `SamGeo.__init__() got an unexpected keyword argument` for both `mask_multplier` and `erosion_kernel`. in colab t4 gpu

also where is this checkpoint file supposed to be saved, originally it was `root/.cache` but i would not find it anywhere, i tried putting in the content folder but its not there either.

**Comment by giswqs** [comment]
The leafmap notebook is outdated. Check the updated version at https://samgeo.gishub.org/examples/satellite. The checkouts are saved to `~/.cache/torch/hub/checkpoints`
