### ISSUE TITLE
to_html Won't Save add_time_slider Feature Correctly via Multiple .png Images

### ISSUE THREAD

**Issue by msw17002** [opengeos/leafmap#493]
**### Environment Information**

-   leafmap version: leafmap-0.22.0
-   Python version: 3.10.6
-   Operating System: CentOS 7 Linux

**### Description**
The add_time_slider feature works as a display on Jupyter Notebook, however, when I save and open the corresponding .html file (using to_html), the time slider isn't visible.
On Jupyter Notebook:
![image](https://github.com/opengeos/leafmap/assets/42711140/03583ada-4ca9-4672-b00e-635c0cfdc7b5)
Saved .html File:
![image](https://github.com/opengeos/leafmap/assets/42711140/5e074ac6-965e-4541-ab77-4bfa65e51796)

**### What I Did**
The script is very simple: 
```
from ipyleaflet import ImageOverlay
from leafmap import leafmap

N,S,E,W = 53,23,-65,-128

layers_dict = {}
for i in range(10):
    feature_id = str(i).zfill(4)

    url = "path_to_pngs/"+feature_id+".png"
    tile_layer = ImageOverlay(url=url,bounds=((S, W), (N, E))) 
    layers_dict[feature_id] = tile_layer

m = leafmap.Map(center=[(N+S)/2, (E+W)/2])
m.fit_bounds([[S,W], [N,E]])
m.add_time_slider(layers_dict, time_interval=1)
m.to_html("mymap.html")
m

```
I attached my .png files and my .html file (mymap.txt) so anyone can duplicate the process.

[pngs.zip](https://github.com/opengeos/leafmap/files/12052280/pngs.zip)
[mymap.txt](https://github.com/opengeos/leafmap/files/12052294/mymap.txt)

**Comment by giswqs** [comment]
ipywidgets won't work in a static HTML. Any custom widgets in leafmap will not work in HTML. If you want to have an interactive web, check out:

- GitHub: https://github.com/opengeos/solara-geospatial
- YouTube: https://youtu.be/_VK10mjwpWI
