### ISSUE TITLE
GeoTIFF is not visible on map, add_raster

### ISSUE THREAD

**Issue by Flawks** [opengeos/leafmap#496]
### Environment Information

-   leafmap 0.22.0:
-   Python 3.10.12
-   Operating System: Google Colab

### Description

I've been trying to run the example notebook with my image in Colab: https://leafmap.org/notebooks/05_load_raster/
The `add_raster` adds the image layer and the leafmap map zooms to the respective coordinates of the GeoTIFF file. However, the image is not visible.

### What I Did
I added some changes to the original notebook:
 - added `!pip install localtileserver` line because otherwise the leafmap map returns the prompt about it failing to cache the image 
 - added `image = 'bogota.tif'` line for the input image that can be obtained from [bogota.tif](https://download.osgeo.org/geotiff/samples/made_up/bogota.tif)

The command I used to add GeoTIFF image to the map:
```
m.add_raster(image)
```
The output of the lefmap map:
![Screenshot_1](https://github.com/opengeos/leafmap/assets/45131492/f28e7845-28eb-4feb-a7d1-f68c64136e29)

How it should look like (QGIS):

![Screenshot_2](https://github.com/opengeos/leafmap/assets/45131492/90d8ee5a-11f8-4dae-82cc-1d91e02a5c9e)

I also tried changing the layers opacity in the map GUI, but it didn't help.

**Comment by giswqs** [comment]
Sounds like a Windows issue. See https://github.com/opengeos/leafmap/issues/492

**Comment by giswqs** [comment]
It works fine on my Linux machine. Try installing localtileserver with conda rather than pip. 

![image](https://github.com/opengeos/leafmap/assets/5016453/50acb2fd-ca6d-474b-b48f-12eae28fdd91)

**Comment by chjones2** [comment]
hello,
I am running into a similar problem. I am trying to run the nb example 91_raster_viz_gui.ipynb but the image is not plotted.

I installed leafmap in a linux machine running Ubuntu. I had some issues creating an environment but eventually it is not giving errors when importing leafmap:

conda create -n pyleafmap python=3.10
pip install leafmap
conda install   ipykernel
python -m ipykernel install --user --name pyleafmap --display-name "Python (pyleafmap)"
pip    install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
conda  install -c conda-forge xarray dask netCDF4 bottleneck
pip    install   rioxarray
pip    install   localtileserver
pip    uninstall matplotlib
pip    uninstall numpy
conda  install -c conda-forge  matplotlib
pip    install   numpy
pip    uninstall leafmap
pip    install leafmap

and here is the notebook:

![2024-08-29_16-48-57](https://github.com/user-attachments/assets/34d0f725-8fc3-412a-a818-f425836a3749)

any ideas are greatly appreciated.

**Comment by giswqs** [comment]
If you have conda, you should avoid using pip to install packages. Try creating a fresh conda env:

```bash
conda create -n geo python=3.11
conda activate geo
conda install -c conda-forge mamba
mamba install -c conda-forge leafmap localtileserver
```

**Comment by ronhlee** [comment]
I'm having the exact same issue,  
Installed using conda following your instruction @giswqs :
- python                    3.13.2          hf636f53_101_cp313    conda-forge
- leafmap                   0.42.12            pyhd8ed1ab_0    conda-forge
- localtileserver           0.10.6             pyhd8ed1ab_0    conda-forge

Any thoughts?

**Comment by chjones2** [comment]
I was never able to fix the issue even using the instructions above

**Comment by giswqs** [comment]
Run the example on Colab https://colab.research.google.com/github/opengeos/leafmap/blob/master/docs/notebooks/32_local_tile.ipynb

**Comment by ronhlee** [comment]
Thanks @giswqs 
I was able to run your example colab notebook. 

However, I ran into the above issue when I tried out another one of your examples [here](https://www.youtube.com/watch?v=CdGqy7UW-8U).

Any idea what might be causing it?
