### ISSUE TITLE
create timelapse animations by pass in list of choropleth maps

### ISSUE THREAD

**Issue by jxlyn** [opengeos/leafmap#497]
### Description

Hi, I want to show the changes of choropleth maps over the time. However, whenever I generate a group of choropleth maps, the legend changes every time. For example, light red represents number from [0,5] in a choropleth map, but on other map, it represents [5,20] because the number in the dataset is different, the classification scheme generates different number range for each color. I'm wondering is it possible to create a feature that shows the changes of a set of choropleth maps over the time using same legend. Thank you!

### Source code

```
Paste your source code here if have sample code to share.
```

**Comment by giswqs** [comment]
leafmap uses mapclassify to create choropleth maps. For your case, I think you can use `mapclassify.UserDefined` to create maps with the same classification scheme, then use `leafmap.create_timelapse()` to merge images as a GIF.

- https://pysal.org/mapclassify/generated/mapclassify.UserDefined.html#mapclassify.UserDefined
- https://leafmap.org/common/#leafmap.common.create_timelapse

**Comment by jxlyn** [comment]
Hi, I was testing to use mapclassify.UserDefined with the tutorial example. But I encountered an error when doing it, I'm wondering how we change the scheme to UserDefined. Could you provide an example? Thank you so much! https://colab.research.google.com/github/opengeos/leafmap/blob/master/examples/notebooks/53_choropleth.ipynb#scrollTo=iyOJ30pLR_ur
![Screenshot 2023-07-19 140000](https://github.com/opengeos/leafmap/assets/75590646/f4d4da90-c49c-4961-a862-88c7dddbfa7d)

**Comment by giswqs** [comment]
Here is an example. 

```python
import leafmap
data = leafmap.examples.datasets.countries_geojson
m = leafmap.Map()
m.add_data(
    data, 
    column='POP_EST', 
    scheme='UserDefined', 
    cmap='Blues', 
    legend_title='Population', 
    classification_kwds={'bins': [1000, 1000000, 10000000, 100000000]}
)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/8aff234e-e1a8-4ea6-9b4a-65df1666e841)
