### ISSUE TITLE
Left/right labels not displaying in split map

### ISSUE THREAD

**Issue by cmspeed** [opengeos/leafmap#498]
### Environment Information

-   leafmap version: 0.23.0
-   Python version: 3.10.12
-   Operating System: macOS Ventura (13.4.1)

### Description
I am using `leafmap.split_map()` to make some split map visualizations using both locally stored tifs and COGs accessed via HTTPS to URL. Everything functions as expected, except that the left/right labels are not displaying on the split map. I am encountering this issue both locally and in a Google Colab runtime. The attached example is the output for two locally stored tifs:

![image](https://github.com/opengeos/leafmap/assets/39209038/074bfb55-7b5d-4b92-93cd-ce4570fa79fc)

### What I Did
For simplicity, the issue may be reproduced using the example code provided in the `leafmap.split_map` [docs](https://leafmap.org/notebooks/12_split_map/).
```
leafmap.split_map(
    left_layer="NLCD 2001 CONUS Land Cover",
    right_layer="NLCD 2016 CONUS Land Cover",
    left_label="2001",
    right_label="2016",
    label_position="bottom",
    center=[36.1, -114.9],
    zoom=10,
)
```
The split map displays as expected, but the labels are not showing up currently. Could this be an issue with my current version of `ipyleaflet` (v.0.17.3)?

Thanks in advance for any help you may be able to provide!

**Comment by giswqs** [comment]
The `leafmap.split_map()` function is being deprecated. Use `Map.split_map()` instead.

```python
m = leafmap.Map(center=[40, -100], zoom=4)
m.split_map(
    left_layer="NLCD 2001 CONUS Land Cover",
    right_layer="NLCD 2016 CONUS Land Cover",
    left_label="2001",
    right_label="2016",
)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/b0c5f947-eb70-425e-8f79-a55ac0150863)

**Comment by cmspeed** [comment]
Awesome, thanks!
