### ISSUE TITLE
add_cog_layer(zoom_to_layer=False) overrides zoom and location set in leafmap.Map

### ISSUE THREAD

**Issue by Chris-AirS** [opengeos/leafmap#507]
### Environment Information

-   leafmap version: 0.23.1
-   Python version: 3.10.11
-   Operating System: Windows

### Description

Using add_cog_layer overrides location and zoom level. 
add_cog_layer()

### What I Did

```
m=leafmap.Map(google_map="HYBRID", location=[-31.562117, 147.194643], zoom=5, locate_control=False, latlon_control=True, draw_export=False, minimap_control=False)
m.add_cog_layer(url=url, zoom_to_layer=False)
m
```

**Comment by giswqs** [comment]
It works fine on my end. Please run `leafmap.Report()` and report the result here. 

```python
import leafmap
m = leafmap.Map()
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
m.add_cog_layer(url, name="Fire (pre-event)", zoom_to_layer=True)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/88e7b384-5c5a-45dd-a3c6-8767542c7135)

**Comment by Chris-AirS** [comment]
Thanks giswqs
The issue in the title was unclear. I've clarified it now.

**Comment by giswqs** [comment]
Again, it works as expected on my end. Setting `zoom_to_layer=False` does not change the map center/zoom level. 

```python
import leafmap
m = leafmap.Map(google_map="HYBRID", location=[-31.562117, 147.194643], zoom=5, locate_control=False, latlon_control=True, draw_export=False, minimap_control=False)
url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
m.add_cog_layer(url, name="Fire (pre-event)", zoom_to_layer=False)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/ce2458b8-7a71-4e8a-884b-376abc412f74)

**Comment by Chris-AirS** [comment]
Thanks again!
Okay so the issue was I had 
import leafmap.foliumap as leafmap
rather than
import leafmap

**Comment by Chris-AirS** [comment]
Actually the location issue still persists. It should centre on the East coast of Australia

**Comment by giswqs** [comment]
Use `center` rather than `location` for ipyleaflet.

```python
import leafmap
m = leafmap.Map(center=[-31.562117, 147.194643], zoom=5)
m
```

**Comment by giswqs** [comment]
The folium bug has been fixed. Run `leafmap.update_package()` and restart the kernel to take effect.

**Comment by Chris-AirS** [comment]
> Use `center` rather than `location` for ipyleaflet.
> 
> ```python
> import leafmap
> m = leafmap.Map(center=[-31.562117, 147.194643], zoom=5)
> m
> ```

Yep. Just noticed that. Thank you
