### ISSUE TITLE
Add palette customisation of cog layers

### ISSUE THREAD

**Issue by Chris-AirS** [opengeos/leafmap#525]
### Description

Allow palette customisation of cog layers
Palette is currently stretched to min/max of data
Could use the vmin and vmax arguments to set the palette min/max

Below the rendered version was output from QGIS with the palette values stretched 0-1000 
The grayscale version is a singleband raster with values between 143-403

Apologies if this already exists using another method. Thanks!

### Source code

```
import leafmap.foliumap as lf

m=lf.Map()
m.add_cog_layer(url='https://temp312432.s3.ap-southeast-2.amazonaws.com/grayscale.tif', palette='plasma', name='grayscale')
m.add_cog_layer(url='https://temp312432.s3.ap-southeast-2.amazonaws.com/rendered.tif', name='rendered')
m.add_colormap(palette='plasma', vmin=0, vmax=1000)
m
```

**Comment by giswqs** [comment]
The `add_cog_layer` method uses TiTiler under the hood. You can use any parameters supported by TiTiler. In this case, you can use `rescale='min,max'` to stretch the image.

https://developmentseed.org/titiler/endpoints/cog/#tiles

```python
import leafmap.foliumap as lf

m=lf.Map()
m.add_cog_layer(
    url='https://temp312432.s3.ap-southeast-2.amazonaws.com/grayscale.tif', 
    palette='plasma', 
    name='grayscale', 
    rescale='0,1000'
    )
m.add_colormap(palette='plasma', vmin=0, vmax=1000)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/3eb65f2c-d776-4f47-9cf4-7bf67345eed8)

**Comment by giswqs** [comment]
By default, if `rescale` is not specified, the function will automatically calculate the statistics of the image and use `percentile_2,percentile98` as `vmin,vmax`, which usually results in better contrast then using the absolute vmin and vmax. 

https://github.com/opengeos/leafmap/blob/master/leafmap/stac.py#L183

**Comment by Chris-AirS** [comment]
Thanks so much for the fix and clarification.
