### ISSUE TITLE
Google's Solar API integration

### ISSUE THREAD

**Issue by sandorkonya** [opengeos/leafmap#533]
### Description

Google has a [Solar API](https://developers.google.com/maps/documentation/solar/geotiff), and the endpoint returns data encoded as GeoTIFF files. One of these is a Surface Model (DSM).
It would be **awesome** to be able to visualise such data with leafmap (which is probably possible).
Below a simple snipplet to retrieve the DSM as a bytestring.

### Source code

Following sniplet retrieves data for a given lat&long.

```
apikey =  "YOUR_KEY_HERE"
url = "https://solar.googleapis.com/v1/dataLayers:get"
params = {
    "location.latitude": 50.97579908646006,
    "location.longitude": 11.023334842349778,
    "radiusMeters": 50,
    "view": "FULL_LAYERS",
    "requiredQuality": "HIGH",
    "pixelSizeMeters": 0.1,
    "key": apikey
}

headers = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
}

solar_data= requests.get(url, params=params, headers=headers)

#the url for the digital height map ---
url = solar_data.json()["dsmUrl"] + "&key=" + apikey
response = requests.get(url, headers=headers)

```

**Comment by giswqs** [comment]
Good suggestion. I tested it. The URL is not a TMS tile URL, so we can't visualize it on the fly. The GeoTIFF file needs to be downloaded locally for visualization. 

![image](https://github.com/opengeos/leafmap/assets/5016453/c74ec837-e76c-40c4-8e5a-1ea4c2f23015)

**Comment by sandorkonya** [comment]
@giswqs nice!
Do you happen to have a dwmo script for that?

**Comment by giswqs** [comment]
I will add functions to leafmap to make it easier to download and visualize the data. 

For now, you can use `leafmap.download_file(url, filename)` to download data.

**Comment by giswqs** [comment]
![Peek 2023-09-06 11-28](https://github.com/opengeos/leafmap/assets/5016453/c3ad58c1-fb2e-465a-80be-900469c7f9fa)

**Comment by sandorkonya** [comment]
@giswqs this looks very promising!
For me RGB, Mask, xxxFlux is working like a charm with `leafmap.download_file` but the dsm does not.

**Comment by giswqs** [comment]
See https://github.com/opengeos/leafmap/blob/master/examples/notebooks/80_solar.ipynb
