### ISSUE TITLE
`add_stac_layer` & `add_mosaic_layer` are broken for STAC mosaicjson files

### ISSUE THREAD

**Issue by prncevince** [opengeos/leafmap#539]
### Environment Information

-   leafmap version: 0.24.1
-   Python version: 3.11.5
-   Operating System: macOS 13.2.1

### Description

Trying to add a STAC mosaicjson layer to Leafmap. We get a similar error compared to #448. A couple examples that have been provided in Leafmap documentation do not work and receive the same error output. 

Reference examples:
- https://leafmap.org/notebooks/67_maxar_open_data/
- https://github.com/opengeos/maxar-open-data

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[], line 3
      1 m = leafmap.Map()
      2 url = 'https://opengeos.github.io/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json'
----> 3 m.add_stac_layer(url, name="Mosaic")
      4 m

File /opt/homebrew/Caskroom/miniforge/base/envs/pygis/lib/python3.11/site-packages/leafmap/foliumap.py:1026, in Map.add_stac_layer(self, url, collection, item, assets, bands, titiler_endpoint, name, attribution, opacity, shown, fit_bounds, **kwargs)
    996 def add_stac_layer(
    997     self,
    998     url: str = None,
   (...)
   1009     **kwargs,
   1010 ):
   1011     """Adds a STAC TileLayer to the map.
   1012 
   1013     Args:
   (...)
   1024         fit_bounds (bool, optional): A flag indicating whether the map should be zoomed to the layer extent. Defaults to True.
   1025     """
-> 1026     tile_url = stac_tile(
   1027         url, collection, item, assets, bands, titiler_endpoint, **kwargs
   1028     )
   1029     bounds = stac_bounds(url, collection, item, titiler_endpoint)
   1030     self.add_tile_layer(
   1031         url=tile_url,
   1032         name=name,
   (...)
   1035         shown=shown,
   1036     )

File /opt/homebrew/Caskroom/miniforge/base/envs/pygis/lib/python3.11/site-packages/leafmap/stac.py:704, in stac_tile(url, collection, item, assets, bands, titiler_endpoint, **kwargs)
    701     else:
    702         r = requests.get(titiler_endpoint.url_for_stac_item(), params=kwargs).json()
--> 704 return r["tiles"][0]

KeyError: 'tiles'
```

### What I Did

You can swap the `url` value below and receive the same error. As well as swap out the `m.add_mosaic_layer` call & still receive a similar `KeyError: 'tiles'` error.

```python
m = leafmap.Map()
url = 'https://opengeos.github.io/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json'
# url = 'https://geospatial.glitch.me/1050050044DE7E00.json'
m.add_stac_layer(url, name="Mosaic")
# m.add_mosaic_layer(url, name="Mosaic")
m
```

**Comment by giswqs** [comment]
The TiTiler endpoint no longer supports masaicjson. See https://github.com/opengeos/leafmap/issues/180#issuecomment-1012985916.

**Comment by prncevince** [comment]
I believe that the Maxar Open Data examples are from 2023. How did those examples in the references previously work? Did you configure a different endpoint? 

Also, you did add support for mosaicjson after #180 was figured out / closed in #206 & #208 right? 

I feel like #180 doesn't tell the whole story here.

**Comment by giswqs** [comment]
I just released v0.24.2 that fixes this issue. Please update the package and try again. Try out this web app: https://huggingface.co/spaces/giswqs/maxar-open-data

```python
m = leafmap.Map()
url = 'https://open.gishub.org/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json'
m.add_stac_layer(url, name="Mosaic")
m
```

**Comment by prncevince** [comment]
Thank you for fixing and upgrading! Screenshot below of output using leafmap version `0.24.2`. I did a `pip install -U leafmap`. However this broke jupyter lab due to pypi dependency resolution, likely on the pyrsistent package, so a `mamba install jsonschema pyrsistent` fixed this.

For what it's worth, redirects from say, the `github.io` domain to another domain, do not seem to work, so the commented line in screenshot below still does not work. 

Also, it would be nice to be able to use **local** mosaicjson / STAC spec files. 

Also, doing something like serving an http web server over localhost and linking to `localhost:8000/1050050044DE7E00.json` does not currently work either. 

<img width="1365" alt="image" src="https://github.com/opengeos/leafmap/assets/17718313/0770dc21-18f3-4fc6-a94b-61a0131727b2">

**Comment by giswqs** [comment]
I already updated the URL last night. See [this](https://github.com/opengeos/maxar-open-data/blob/master/examples/turkey_earthquake.ipynb).

The TiTiler endpoint is required to redner the mosaicjson. I don't think it supports rendering mosaicjons stored locally.

**Comment by giswqs** [comment]
If you have a resolution for rendering local mosaicjson files, let me know. I would be happy to add leafmap support for it.

**Comment by prncevince** [comment]
The updated URLs make sense. I'm referring to the fact that redirects error. 

There seems to be scarce resources showing how to use the mosaicjson API endpoint? It's mentioned briefly in the Create Mosaic section of the Working with MosaicJSON notebook of the TiTiler docs:

- https://developmentseed.org/titiler/examples/notebooks/Working_with_MosaicJSON/#5-create-mosaic

Below are 2 examples that show use of the TiTiler RESTful API mosaicjson endpoint, one using your example on Maxar Open Data & the other using the example out of the TiTiler docs.

- https://titiler.xyz/mosaicjson/tilejson.json?url=https://gist.githubusercontent.com/vincentsarago/c6ace3ccd29a82a4a5531693bbcd61fc/raw/e0d0174a64a9acd2fb820f2c65b1830aab80f52b/NOAA_Nashville_Tornado.json 
- https://titiler.xyz/mosaicjson/tilejson.json?url=https://open.gishub.org/maxar-open-data/datasets/Kahramanmaras-turkey-earthquake-23/1050050044DE7E00.json

I tried using the `?url=file:///` option as specified in the [**old** cogeo-mosaic-tiler docs](https://github.com/developmentseed/cogeo-mosaic-tiler/blob/master/doc/API.md#mosaicjson-path) where using the old version of the mosaicjson endpoint had documentation for running requests on local mosaicjson files, but this gives a `[Errno 2] No such file or directory` error.

**Comment by giswqs** [comment]
Leafmap already uses the TiTiler demo endpoint to render mosaicjson files available throught HTTP. I don't think it supports reading local mosaicjson files.
