### ISSUE TITLE
74_map_tiles_to_geotiff.ipynb

### ISSUE THREAD

**Issue by sandorkonya** [opengeos/leafmap#540]
### Environment Information

https://leafmap.org/notebooks/74_map_tiles_to_geotiff/  - opened on colab
  
### Description

got error by running the notebook and using OSM as basemap.

### What I Did

added a bbox on the map: [1.909, 47.9013, 1.9118, 47.9024]
changed the source basemap (to default == OSM)

![image](https://github.com/opengeos/leafmap/assets/6852967/91eb9e54-624f-48f7-b592-24271317c8e2)

```
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/leafmap/common.py](https://localhost:8080/#) in map_tiles_to_geotiff(output, bbox, zoom, resolution, source, crs, to_cog, quiet, **kwargs)
   9317     try:
-> 9318         draw_tile(source, south, west, north, east, zoom, output, quiet, **kwargs)
   9319         if crs.upper() != "EPSG:3857":

7 frames
HTTPError: 403 Client Error: Forbidden for url: https://tile.openstreetmap.org/15/16557/11403.png

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/leafmap/common.py](https://localhost:8080/#) in map_tiles_to_geotiff(output, bbox, zoom, resolution, source, crs, to_cog, quiet, **kwargs)
   9322             image_to_cog(output, output)
   9323     except Exception as e:
-> 9324         raise Exception(e)
   9325 
   9326 

Exception: 403 Client Error: Forbidden for url: https://tile.openstreetmap.org/15/16557/11403.png
```

**Comment by giswqs** [comment]
The OpenStreetMap example has been removed. Please check the updated version. 
https://leafmap.org/notebooks/74_map_tiles_to_geotiff/

**Comment by sandorkonya** [comment]
Thank you,

after reviewing the [original repo](https://github.com/gumblex/tms2geotiff/blob/master/tms2geotiff.py#L26),
probably a session header would solve the error.

regards!

**Comment by giswqs** [comment]
Good suggestion. I did not realize that I missed the session header. It worked before without. Not sure why it stopped working suddenly. I have added the session header in #541. You can run `geemap.update_package()` and restart the kernel to take effect.
