### ISSUE TITLE
Download_ned.ipynb does not return any data

### ISSUE THREAD

**Issue by leiwanglsu** [opengeos/leafmap#548]
### Environment Information

-   leafmap version: 0.24.4
-   Python version: 3.10.12
-   Operating System: Google colab

### Description
The script cannot find any data, and the returned results is NoneType

### What I Did
Opened the download_ned.ipynb in colab
Run the code by blocks 
```
leafmap.download_ned(region, return_url=True)

{'message': 'Endpoint request timed out'}
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-6-43b619e56a6c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 leafmap.download_ned(region, return_url=True)

1 frames
[/usr/local/lib/python3.10/dist-packages/leafmap/common.py](https://localhost:8080/#) in find_tiles(self, region, return_type, geopandas_args, API)
   5497         results = self.find_details(**API)
   5498         if return_type == "list":
-> 5499             return [i["downloadURL"] for i in results.get("items")]
   5500         return results
   5501 

TypeError: 'NoneType' object is not iterable
```

**Comment by giswqs** [comment]
Sometimes it is the USGS server issue. I just tried it, and it seems working fine. Try again. 

![image](https://github.com/opengeos/leafmap/assets/5016453/1273884b-8a0d-4313-8efa-0bb5e1c7451f)

**Comment by giswqs** [comment]
Closing this for now. Feel free to reopen if the issue persists.
