### ISSUE TITLE
Browser specific failure with add_raster on sagemaker

### ISSUE THREAD

**Issue by ldemaz** [opengeos/leafmap#570]
### Environment Information

-   leafmap version: 0.27.0
-   Python version: Python 3.8.17
-   Operating System: Mac OS 10.15.7

### Description
leafmap running on sagemaker studio seems to have a browser-specific failure with `add_raster`. A local raster will display on leafmap using `add_raster`, provided Chrome is the browser, whereas no raster appears on Firefox and Edge. This finding was confirmed in a class in which multiple students were using Chrome, two using Edge, and I was using Firefox. And I have confirmed on the same machine that it works with Chrome but not Firefox (118.0.1). 

### What I Did
The [notebook](https://github.com/agroimpacts/nmeo/blob/class/f2023/materials/code/notebooks/sagemaker-geo-demo.ipynb) here shows the failure. It is lengthy but self-contained. The failure occurs at the [Map It section](https://github.com/agroimpacts/nmeo/blob/37aa7f01bc761dd48a1e1cf0d6721a7246f74fa1/materials/code/notebooks/sagemaker-geo-demo.ipynb#L612).

**Comment by giswqs** [comment]
@ldemaz Thanks for reporting and providing the reproducible example. I will explore it. This is most likely an issue of the upstream localtileserver package @banesullivan

**Comment by banesullivan** [comment]
I'll add this to my list of things to check/fix in localtileserver. Hopefully I'll have an update in the coming weeks

**Comment by banesullivan** [comment]
I've tested the next release of localtileserver agains Chrome, Arc, Firefox, and Safari and all seems to be working.

Perhaps try to upcoming release (0.10): 

```
pip install --pre --no-cache localtileserver
```
