### ISSUE TITLE
Popups for PMTiles Layers

### ISSUE THREAD

**Issue by daniel-fink** [opengeos/leafmap#571]
Is there a way to add popups (on hover/click) for features on PMTiles layers?

(e.g. akin to MaplibreGL `maplibregl.Popup()` function -- https://maplibre.org/maplibre-gl-js/docs/examples/popup-on-click/)

**Comment by giswqs** [comment]
Leafmap uses [folium-pmtiles](https://github.com/jtmiclat/folium-pmtiles) to under to hood to render PMTiles. I would encourage you to open an issue at https://github.com/jtmiclat/folium-pmtiles/issues. I am not a JavaScript user. It is challenging for me to add support for this.
