### ISSUE TITLE
'numpy.ndarray' object has no attribute 'interp'

### ISSUE THREAD

**Issue by kongdd** [opengeos/leafmap#577]
A small bug:

In L3699, `np_array.interp` should be `np.interp`, as the 'numpy.ndarray' object has no attribute 'interp'.

https://github.com/opengeos/leafmap/blob/5d9cd0ffc77e7bea004b801777684e04926a458a/leafmap/common.py#L3699

![image](https://github.com/opengeos/leafmap/assets/9815742/85256e4d-40f0-482b-b548-9a85c43a9463)

![image](https://github.com/opengeos/leafmap/assets/9815742/e07d3598-fdd8-4ada-91cf-ae287aafde3a)

**Comment by giswqs** [comment]
Good catch. I would encourage you to submit a pull request to fix this so that you can be recognized as a contributor to the project.

**Comment by kongdd** [comment]
Thank you. PR is pushed.
