### ISSUE TITLE
lonboard map to_streamlit

### ISSUE THREAD

**Issue by jc9677** [opengeos/leafmap#594]
Leafmap is fantastic and it's great to see support for lonboard already. I'm not sure how easy or difficult it would be to add a **to_streamlit** method for lonboard maps, but this would be useful for me!

**Comment by giswqs** [comment]
lonboard has the to_html() method. It should be straightforward to add a to_streamlit() method, similar to the folium method. I will add that when I have time. Contributions are welcome.

**Comment by giswqs** [comment]
It appears the HTML generated by lonboard has something special. It does not work with the streamlit html component. See https://github.com/opengeos/leafmap/pull/600. I don't have a solution yet.

**Comment by giswqs** [comment]
The same method works fine for folium maps.

**Comment by cboettig** [comment]
@giswqs do you have an example of this?  in my testing I'm just getting a literal data item back,

![image](https://github.com/opengeos/leafmap/assets/222586/33513c0b-8ab8-47a6-88a7-1fd68a389109)

```python
import streamlit as st
import leafmap.deckgl as lonboard
st.set_page_config(page_title="Lonboard Test")
m = lonboard.Map(center=[35, -100], zoom=3)
m.to_streamlit()
```

**Comment by giswqs** [comment]
I have not used lonboard recently. The lonbard might have changed. Let me know look into it.

**Comment by giswqs** [comment]
This seems a lonboard problem. The `to_streamlit()` method does not have any special. 

```python
    def to_streamlit(
        self,
        width: Optional[int] = None,
        height: Optional[int] = 600,
        scrolling: Optional[bool] = False,
        **kwargs,
    ):

        try:
            import streamlit.components.v1 as components

            return components.html(
                self.to_html(), width=width, height=height, scrolling=scrolling
            )

        except Exception as e:
            raise e


```
![image](https://github.com/opengeos/leafmap/assets/5016453/7612864e-7443-4047-ada0-73de0441c274)
