### ISSUE TITLE
Leafmap and streamlit cannot use interactive vector tools to obtain coordinate values

### ISSUE THREAD

**Issue by CraibYun** [opengeos/leafmap#611]
### Environment Information

-   leafmap version:0.18.8
-   Python version:3.9.16
-   Operating System:windows

### Description

Leafmap and streamlit cannot use the interactive vector tool to obtain coordinate values. The possible reason is that the program will refresh and run as soon as the button is clicked.

### What I Did

```
import os
import streamlit as st
import leafmap as leafmap

st.set_page_config(layout="wide")

Map = leafmap.Map()
col1, col2 = st.columns([4, 1])
   
with col2:
    addButton3=st.button('get range')
    if addButton3:
        bbox=Map.user_roi_bounds()
        st.markdown("{}".format(bbox))
        
with col1:
    Map.to_streamlit(height=750)
```
In addition, when using the 'leafmap' library in streamlit, the Map.add_raster function cannot load the local raster normally, but at the same time, the add_raster function of 'leafmap.foliumap' can be displayed normally in the streamlit map. What is the reason?
![1111](https://github.com/opengeos/leafmap/assets/114090830/4c1104fa-6da8-4a20-817e-c3031994893a)

**Comment by giswqs** [comment]
The add_raster will not work with streamlit. Don't waste your time on this. 

Try solara: https://huggingface.co/spaces/giswqs/solara-geospatial
