### ISSUE TITLE
Integrate the earthaccess Python package

### ISSUE THREAD

**Issue by giswqs** [opengeos/leafmap#620]
search, download or stream NASA Earth science data
https://earthaccess.readthedocs.io/en/latest/

**Comment by betolink** [comment]
Qiusheng, if you need any help or guidance with earthaccess don't hesitate to ask me or any of the maintainers. I think incorporating NASA datasets to Leafmap will be a nice addition to this already fantastic package!

**Comment by giswqs** [comment]
Will do. Thank you
