### ISSUE TITLE
Show parameter seems to be ignored when using any of the google maps basemaps

### ISSUE THREAD

**Issue by ruwfr** [opengeos/leafmap#621]
### Environment Information
-   leafmap version: 0.29.4
-   Python version: 3.11.4
-   Operating System: Windows

### Description
I want to add a "HYBRID" basemap to my map but not show it. It should only be shown when explicitly selected in the LayerControl.

### What I Did
```
import leafmap.foliumap as leafmap
map = leafmap.Map(
    draw_control=False,
    measure_control=False,
    fullscreen_control=False,
    zoom_start=17,
)
map.add_basemap(basemap="HYBRID", show=False)
map.save("map.html")
```

### What happened
the HYBRID layer is selected in the LayerControls and shown, even though show is set to False. When using a different tiles provider, such as SafeCast, the behaviour is as expected and the layer is not selected and not shown.

**Comment by giswqs** [comment]
Good catch. I am looking into it now.

**Comment by giswqs** [comment]
Seems the issue is with the folium backend. The ipyleaflet backend works as expected. 

```python
import leafmap

m = leafmap.Map()
m.add_basemap('HYBRID', show=False)
m
```

**Comment by giswqs** [comment]
It has been fixed. Run `leafmap.update_package()` and restart the kernel to take effect.
