### ISSUE TITLE
lidar_vix.ipynb notebook leafmap functions not supported in colab

### ISSUE THREAD

**Issue by VRConservation** [opengeos/leafmap#625]
### Environment Information

- google colab

### Description

The visualize using pyvista, ipygany, panel, open3d backends do not work when running the lidar_viz.ipynb notebook in Colab.  The result is an error message: 'This function not supported in Google Colab.':

![image](https://github.com/opengeos/leafmap/assets/61313347/771956fd-8abd-4bf1-bfb8-0756eafacbe4)

**Comment by VRConservation** [comment]
OK, thanks. But the notebooks have the open in colab icon. Might be worth removing those!

**Comment by giswqs** [comment]
The Colab badge appear on all notebooks.  The error message on the notebook should be sufficient in informing users when certain features are not supported on Colab.
