### ISSUE TITLE
Feature Request: Simplified Method to Add Single Markers to Leafmap

### ISSUE THREAD

**Issue by Niko-La** [opengeos/leafmap#633]
### Description
Currently, to add a marker or a point to a `leafmap` Map object, users need to create a DataFrame and use the `add_xy_data` method. This process can be overly complex for cases where only a single point or marker needs to be added to the map.

### Proposed Feature
I propose adding a feature that allows users to easily place a single marker, pin, or dot on the map without the need to create a DataFrame. Ideally, this feature would enable specifying the marker type (e.g., "pin" or "dot") and customizing its appearance, such as choosing the color through a hex code.

adding an png file is another option

### Use Case
For example, if a user simply wants to mark a specific location on the map

```
m = leafmap.Map(
         marker = 'pin'
         center=[50, 19], 
         zoom=4)  # center=[lat, lon]
m
```

**Comment by giswqs** [comment]
Good suggestion. I will implement it.

**Comment by giswqs** [comment]
This has been implemented. See https://leafmap.org/notebooks/86_add_markers/
