### ISSUE TITLE
Error while running an executable file prepared from leafmap, wxpython, pyinstaller

### ISSUE THREAD

**Issue by ravish-bapna** [opengeos/leafmap#636]
I created a conda environment and installed few packages (leafmap, wxpython, geopandas, shapely, pyinstaller). Then I created an executable file from code (shared as python code.txt) using pyinstaller. After running the generated executable file, an error message is displayed (shared as error message.txt). Kindly guide me to resolve the error. Thanks in advance.

[error message.txt](https://github.com/opengeos/leafmap/files/13611757/error.message.txt)
[python code.txt](https://github.com/opengeos/leafmap/files/13611759/python.code.txt)

**Comment by giswqs** [comment]
I am not familiar with wxpython or pyinstaller. I am not sure how you installed leafmap. You can find the missing file here.
https://github.com/opengeos/leafmap/blob/master/leafmap/examples/datasets.txt
