### ISSUE TITLE
Installation Issue: Failed to Install leafmap[vector] due to GDAL Dependency Error in JupyterLab and Colab

### ISSUE THREAD

**Issue by Niko-La** [opengeos/leafmap#640]
Tried this on local jupyterlab and colab.

Looks like GDAL, is there a simple way to get it. This probably will be a huge barrier to newer mapping and data visualization enthusais not familiar with conda, env etc

When attempting to install the `leafmap[vector]` package in both local JupyterLab and Google Colab environments, I encountered an issue related to the GDAL dependency. Despite `leafmap[vector]` and its dependencies being listed as satisfied, the installation failed while attempting to build the wheel for Fiona (a dependency of Geopandas, which is required by `leafmap[vector]`).

The specific error encountered is related to GDAL configuration:
```
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [3 lines of output]
    <string>:86: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
    WARNING:root:Failed to get options via gdal-config: [Errno 2] No such file or directory: 'gdal-config'
    CRITICAL:root:A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.
[end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
```

This error appears to be a major barrier for new enthusiasts in mapping and data visualization who might not be familiar with more complex environments like Conda. Is there a simpler way to resolve this GDAL dependency issue to facilitate the installation of `leafmap[vector]`?

**Comment by giswqs** [comment]
This is a GDAL installation issue rather than a leafmap issue. Colab already has `gdal` preinstalled. It should work with Colab just fine. 

Alternatively, you can run the following to install GDAL before install `leafmap[vector]`. 

```bash
pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
```
