### ISSUE TITLE
`legend_position` never accessed for foliumap in `add_data` method

### ISSUE THREAD

**Issue by avnigo** [opengeos/leafmap#644]
I had to use multiple legends and discovered they overlap, even when I define the `legend_position` parameter in the `add_data()` method. Following the code, I saw that `legend_position` can be passed but is never accessed in `foliumap.py`, unlike in `leafmap.py` as seen in the following:

https://github.com/opengeos/leafmap/blob/d360f6a8c43d90a91dcfb06e198bf4e03f08973f/leafmap/foliumap.py#L2721

https://github.com/opengeos/leafmap/blob/d360f6a8c43d90a91dcfb06e198bf4e03f08973f/leafmap/foliumap.py#L2857-L2858

https://github.com/opengeos/leafmap/blob/d360f6a8c43d90a91dcfb06e198bf4e03f08973f/leafmap/leafmap.py#L4071-L4074

I understand moving the legend is an open issue in folium https://github.com/python-visualization/folium/issues/1605, and that the `legend_position` parameter is kept there for interoperability with `ipyleaflet` in `common.py`, but perhaps a note in the docstrings or a warning like raising `NotImplementedError` might be helpful when attempting to debug why it doesn't work.

https://github.com/opengeos/leafmap/blob/d360f6a8c43d90a91dcfb06e198bf4e03f08973f/leafmap/foliumap.py#L2751

**Comment by giswqs** [comment]
The legend position can be set when `draggable=False`

```python
m = leafmap.Map(draw_control=False, scale_control=False, measure_control=False)
m.add_legend(builtin_legend='NLCD', position='bottomleft', draggable=False)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/d776c1e7-78d9-4ffc-be84-c09dfcaeef1f)

**Comment by avnigo** [comment]
That's great, it works using `draggable=False` with `add_legend` – thanks!

I never actually got `draggable=True` to work for dragging the legend in foliumap, but I think that might be because I'm using [st_folium](https://github.com/randyzwitch/streamlit-folium), so I haven't looked more into it. However, with it `False`, it solves the legend position issue.

Thanks again!

**Comment by giswqs** [comment]
I am not sure about streamlit, but it should work with Jupyter Notebook. 

![Peek 2023-12-20 11-07](https://github.com/opengeos/leafmap/assets/5016453/b690ef2f-0e63-4691-b27c-96f0735b4774)

**Comment by avnigo** [comment]
That makes sense, I haven't tried it in a Jupyter Notebook, but I did see your commit about it on [geemap](https://github.com/gee-community/geemap/issues/224), wasn't sure it worked on leafmap too. Good to know!
