### ISSUE TITLE
leafmap.array_to_image generated wrong transform when not using source GeoTIFF

### ISSUE THREAD

**Issue by Yimsun97** [opengeos/leafmap#659]
### Environment Information

-   leafmap version: 0.30.1
-   Python version: 3.9.18
-   Operating System: Windows 10

### Description

I want to add a raster file (xr.DataArray) in the memory on the map before saving to the disk. Based on the leafmap tutorial ["89 image array viz"](https://leafmap.org/notebooks/89_image_array_viz/), I used the `leafmap.array_to_image` function to convert the xr.DataArray to the correct format that can be recognized by the `map.add_raster`.

### What I Did

1. I found that map.add_raster generated what I expected if a string of path is assigned.
```
m = leafmap.Map()
m.add_raster('./worldmap.tif', cmap='coolwarm', layer_name='worldmap')
m
```
This will give the fig1 (as expected).
![fig1](https://github.com/opengeos/leafmap/assets/38037741/37e91a86-80c2-40c7-8e82-e661b2e2e14a)

2. When I open that file using rioxarray and using the `source` parameter, it also worked as expected:
```
world = rioxarray.open_rasterio('./worldmap.tif')
world_img = leafmap.array_to_image(world, source='worldmap.tif')
m = leafmap.Map()
m.add_raster(world_img, cmap='coolwarm', layer_name='worldmap')
m
```
This will give the fig2 (as expected).
![fig2](https://github.com/opengeos/leafmap/assets/38037741/52f5b1f4-ca65-4620-ae9f-702eaa4f7bb5)

3. However, it failed when I assigned the `cellsize`, `crs`, and `transform` parameters. It seemed that the memory file got the wrong transformation or projection. As there is no example in the tutorial notebook, I'm wondering how to set these parameters to get the in-memory file visualized before saving to disk?
```
world = rioxarray.open_rasterio('./worldmap.tif')
world_img = leafmap.array_to_image(world, cellsize=0.5, crs='EPSG:4326')
m = leafmap.Map()
m.add_raster(world_img, cmap='coolwarm', layer_name='worldmap')
m
```
This will give the fig3 (maybe due to wrong projection).
![fig3](https://github.com/opengeos/leafmap/assets/38037741/774074d6-41a3-4080-b694-027b42ae5d39)

The GeoTIFF and the notebook files I used are attached. Thanks in advance for your time! 

[worldmap.zip](https://github.com/opengeos/leafmap/files/13939704/worldmap.zip)
[leafmap_array_to_image.zip](https://github.com/opengeos/leafmap/files/13939715/leafmap_array_to_image.zip)

**Comment by giswqs** [comment]
You also need to set the transform parameter so that the extent of the image is correctly set. Use rasterio to check the transform info on the source

**Comment by giswqs** [comment]
I found the bug. Fixing it now.
