### ISSUE TITLE
add_raster() results in TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by mkoenig3** [opengeos/leafmap#670]
### Environment Information

-   leafmap version: 0.30.1
-   localtileserver version: 0.10.0
-   Python version: 3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]
-   Operating System: Linux 5.10.178-162.673.amzn2.x86_64

### Description

Hey there, 

I am trying to follow this tutorial: https://leafmap.org/notebooks/89_image_array_viz/ but quickly run into a TypeError.

Many thanks for your help and kudos for leafmap!
Marcel

### What I Did

```
import leafmap
import rasterio
import rioxarray
import xarray as xr

url1 = "https://open.gishub.org/data/raster/landsat7.tif"
url2 = "https://open.gishub.org/data/raster/srtm90.tif"
satellite = leafmap.download_file(url1, "landsat7.tif")
dem = leafmap.download_file(url2, "srtm90.tif")

dataset = rasterio.open(satellite)
nir = dataset.read(1).astype(float)
red = dataset.read(2).astype(float)
ndvi = (nir - red) / (nir + red)

ndvi_image = leafmap.array_to_image(ndvi, source=satellite)

m = leafmap.Map()
m.add_raster(satellite, band=[1, 2, 3], nodata=-1, layer_name="Landsat 7")
m.add_raster(ndvi_image, cmap="Greens", layer_name="NDVI")
m
```

This is the TypeError I receive:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[23], line 19
     16 ndvi_image = leafmap.array_to_image(ndvi, source=satellite)
     18 m = leafmap.Map()
---> 19 m.add_raster(satellite, band=[1, 2, 3], nodata=-1, layer_name="Landsat 7")
     20 m.add_raster(ndvi_image, cmap="Greens", layer_name="NDVI")
     21 m

File /opt/conda/lib/python3.11/site-packages/leafmap/leafmap.py:2237, in Map.add_raster(self, source, band, palette, vmin, vmax, nodata, attribution, layer_name, zoom_to_layer, visible, **kwargs)
   2235 if not hasattr(self, "cog_layer_dict"):
   2236     self.cog_layer_dict = {}
-> 2237 band_names = list(tile_client.metadata()["bands"].keys())
   2238 params = {
   2239     "tile_layer": tile_layer,
   2240     "tile_client": tile_client,
   (...)
   2244     "type": "LOCAL",
   2245 }
   2246 self.cog_layer_dict[layer_name] = params

TypeError: 'dict' object is not callable
```

**Comment by giswqs** [comment]
Thank you for reporting. This is probably due to the recent localtilesever updates. See PR https://github.com/opengeos/leafmap/pull/666. I will look into it. A temporary workaround is to install localtileserver v0.7.2

**Comment by giswqs** [comment]
This issue has been fixed in #666. Will release a new version soon.

**Comment by mkoenig3** [comment]
Wow, that was an incredible quick fix. Thanks you very much and keep up the great work!

**Comment by floriandeboissieu** [comment]
@mkoenig3 did you manage to get the raster redenred after that fix?
On my side, I do not have the TypeError anymore, but the raster simply does not render (only the basemap), like in https://leafmap.org/notebooks/89_image_array_viz/

I also tried that notebook on binder, and same result, a basemap but still no raster render

**Comment by floriandeboissieu** [comment]
Actually, my problem was coming from port forwarding under a remote ssh vscode, cf https://github.com/banesullivan/localtileserver/issues/181.

Adding a port and forwaring it in vscode solved the problem: `m.add_raster("myfile.tif", port=xxxx)`
