### ISSUE TITLE
Cannot get pixel values with inspector tool (notebook 89)

### ISSUE THREAD

**Issue by ZZMitch** [opengeos/leafmap#688]
### Environment Information

-   leafmap version: 0.31.2
-   Python version: 3.11
-   Operating System: Windows 10

### Description

I completed notebook 89 without issues. However, when exploring the data in the interactive map, the inspector tool only provides the lat/lon location and provides a TypeError rather than the pixel value. The code is unchanged from notebook 89. 

### What I Did

![image](https://github.com/opengeos/leafmap/assets/78507308/e6240e1d-2c89-4db9-ad7b-6eb3aa14a22c)

```
m = leafmap.Map()
m.add_raster(satellite, band=[1, 2, 3], nodata=-1, layer_name="Landsat 7")
m.add_raster(ndvi_image, colormap="Greens", layer_name="NDVI")
m
```

**Comment by giswqs** [comment]
Thank you for reporting. This issue has been fixed in #689. Will release a new version tomorrow.
