### ISSUE TITLE
Italian Cadastre WMS in leafmap

### ISSUE THREAD

**Issue by agronomofiorentini** [opengeos/leafmap#691]
### Environment Information

-   leafmap version: 0.23.2
-   Python version: Python 3.10.4
-   Operating System: Windows

### Description

First of all, I want to thank you for the immense work you are doing for the whole spatial data community in python

I would like to add the Italian Cadastre WMS service to the leafmap.

The Italian cadastre releases this service wms under by License CC-BY 4.0.

The following is the code that i am using, but the map is displaying wrong. 

I have checked the documentation of the Italian Cadastre WMS and the coordinate reference system by default EPSG:6706

### What I Did

```
import leafmap.leafmap as leafmap

m = leafmap.Map()

catasto_wms_url ="https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap"
layer_particelle = "Cartografia_Catastale"

m.add_wms_layer(url=catasto_wms_url, 
                layers=layer_particelle,
                name="CP.CadastralParcel", 
                format="image/png", 
                show=True, 
                attribution="Agenzia delle Entrate")

m
```

The map is seen in a distorted way.

Thanks

**Comment by giswqs** [comment]
This seems an issue with the data layer. It does not render properly in QGIS, either. 

![image](https://github.com/opengeos/leafmap/assets/5016453/cc71814a-6e6a-4683-b416-446cbddc2d28)

![image](https://github.com/opengeos/leafmap/assets/5016453/80c6852f-9455-434b-af18-ef4c55d55dee)

**Comment by agronomofiorentini** [comment]
I really don't know how to operate with such wms in leafmap

**Comment by giswqs** [comment]
Sorry, I don't think this is a leafmap issue. Try the following folium example without leafmap. It does not work seem to work. I don't think folium support WMS layers with a custom projection. You might want to open an issue on the [folium repo](https://github.com/python-visualization/folium). 

https://python-visualization.github.io/folium/latest/reference.html#module-folium.raster_layers
```python
import folium

m = folium.Map(location=[47.46901, 9.36688], zoom_start=13)

folium.raster_layers.WmsTileLayer(url = 'https://wms.cartografia.agenziaentrate.gov.it/inspire/wms/ows01.php?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap',
                                  layers = 'Cartografia_Catastale',
                                  transparent = True, 
                                  control = True,
                                  fmt="image/png",
                                  name = 'wms',
                                  overlay = True,
                                  show = True,
                                  ).add_to(m)
folium.LayerControl().add_to(m)

m
```
