### ISSUE TITLE
Doesn't work in Kaggle notebooks

### ISSUE THREAD

**Issue by openSourcerer9000** [opengeos/leafmap#707]
### Environment Information

-   leafmap version: 0.31.5
-   Python version: 3.10
-   Operating System: Linux

It just prints "loading widget",  but won't display a map. It seems it does work with folium backend; Maybe it should fall back to using folium  when it can't display. 
![image](https://github.com/opengeos/leafmap/assets/61931826/8b999d76-eccb-4276-8652-470ebc33fedf)

https://www.kaggle.com/code/opensourcerer9000/leafmap-hello-world

**Comment by giswqs** [comment]
This is probably anipyleaflet installation issue. Try the following. If it doesn't work, please report it to the ipyleaflet repo.

import ipyleaflet 
m = ipyleaflet.Map()
m

**Comment by giswqs** [comment]
One workaround is to use the folium backend.

import leafmap.foliumap as leafmap
m = leafmap.Map()
m

**Comment by openSourcerer9000** [comment]
That seems to be where it's coming from, I passed the buck down to ipyleaflet
