### ISSUE TITLE
Satellite Imagery not working!

### ISSUE THREAD

**Issue by pabhermoso** [opengeos/leafmap#713]
Suddenly this morning the Satellite version is not working:

m = leafmap.Map(minimap_control=True)
m.add_basemap("SATELLITE")
m.to_streamlit(height=500)

**Comment by giswqs** [comment]
It works fine on my end. Please try again. 

![image](https://github.com/opengeos/leafmap/assets/5016453/46085013-4a32-4b7b-8ffb-f371cece6da8)
