### ISSUE TITLE
streamlit bidirectional works with some layers but not others

### ISSUE THREAD

**Issue by cboettig** [opengeos/leafmap#726]
### Environment Information

- leafmap version: leafmap==0.31.7
- Python version: 3.10.12
- Operating System: Ubuntu Linux

### Description

adding `bidirectional = True` option to `m.to_streamlit(bidirectional = True)` prevents some layer types such as `m.add_pmtiles()` and `m.add_tile_layer()` from rendering.  However, other layer types such as `m.add_cog_layers()` render just fine.  (I think you know about this already but thought it might help to have some issue to track it).

**Comment by giswqs** [comment]
I guess those functions injeting some JavaScript code into the map, which may present the streamlit-folium package from functioning properly. You will need to report the issue to the [streamlit-folium](https://github.com/randyzwitch/streamlit-folium) repo. I don't know JavaScript well enough to resolve the issue. 

https://github.com/opengeos/leafmap/blob/0a83b3e54419f0a216fb41d3474c258d54d02b82/leafmap/foliumap.py#L1861-L1865

**Comment by cboettig** [comment]
ok perfect, will do.  I'll see if I can work up some examples with pure streamlit-folium so I can file a decent bug report there.

**Comment by cboettig** [comment]
resolved in the recent release of streamlit-folium.

**Comment by giswqs** [comment]
Nice! Thanks for the update
