### ISSUE TITLE
Vector tile layer control doesn't work

### ISSUE THREAD

**Issue by lopezvoliver** [opengeos/leafmap#747]
### Environment Information

-   leafmap version: 0.32.1
-   Python version: 3.12.3
-   Operating System:  Ubuntu 22.04.4 LTS

### Description

Adding a vector tile layer, I expect the control to turn on/off the layer to work, but the layer remains in the map. 

#### Example using ipyleaflet without leafmap (expected behavior)

```python
import ipyleaflet
m = ipyleaflet.Map(center=[30.25, 38.25],zoom=10)

styles = {
    "fields":{
        "fillOpacity": 1,
        "fillColor": "#aefeae",
        "fill": True,
        "weight": 1,
        "color": "black",
        "opacity": 1
    }
}
url_data = "path/to/my/vector-tile-layer/{z}/{x}/{y}.pbf"
vl = ipyleaflet.VectorTileLayer(url=url_data, vector_tile_layer_styles=styles, name="Fields")
m.add_layer(vl)
control = ipyleaflet.LayersControl(position='topright')
m.add(control)
m
```

![ipyleaflet](https://github.com/opengeos/leafmap/assets/14804652/d0a8434e-06d1-450d-92e5-3a5ae487e220)

#### Example using leafmap (bug)

```python
import ipyleaflet
import leafmap
m = leafmap.Map(center=[30.25, 38.25],zoom=10)

styles = {
    "fields":{
        "fillOpacity": 1,
        "fillColor": "#aefeae",
        "fill": True,
        "weight": 1,
        "color": "black",
        "opacity": 1
    }
}
url_data = "path/to/my/vector-tile-layer/{z}/{x}/{y}.pbf"
vl = ipyleaflet.VectorTileLayer(url=url_data, vector_tile_layer_styles=styles, name="Fields")
m.add_layer(vl)
#m.add_vector_tile(url_data,styles, "Field use")  # Same issue
m
```

![leafmap](https://github.com/opengeos/leafmap/assets/14804652/88b3193c-44ca-4df1-8cd8-c002f36b8c48)

**Comment by lopezvoliver** [comment]
Here's another clue: if I add the simple `ipyleaflet.LayersControl`, it does work.. so the issue is with the leafmap toolbar:

![leafmap_wcontrol](https://github.com/opengeos/leafmap/assets/14804652/2f1edbdd-f607-4193-9bae-2268ea0fd0dd)

**Comment by giswqs** [comment]
This is probably an ipyleaflet issue because the VectorTileLater class doesn't have an attribute for toggling the layer off programmatically, e.g., layer.visible=False

https://ipyleaflet.readthedocs.io/en/latest/layers/vector_tile.html

**Comment by lopezvoliver** [comment]
Was just about to comment.. yes I found this out. However, a similar strategy could be used as for the geojson. I'm able to do something like:

```python
for l in layers:
    if l.name=="Fields":
        l.vector_tile_layer_styles = {'fields':{'fillOpacity':0, 'opacity':0}}
```

which worked to make it invisible. This could be adapted but it will involve keeping track of the original styles and names used for these layers. I'll work on this anyway independently, but if I manage to make it work in leafmap, I'll make a PR.

**Comment by giswqs** [comment]
Sounds good. Thanks.

**Comment by zvezdi** [comment]
Hello :) I'm working on a project for a university course I'm taking and I hit a similar issue.

Same problem is reproducible with `add_circle_markers_from_xy` when you pass different names with the `layer_name` parameter. The layers names are visible when you open the toolbox but visibility and opacity changes are not applied to the map.

I just started familiarising myself with the library so I might be just using it wrong. This is how I try to use it:

```python
map = leafmap.Map()
map.add_circle_markers_from_xy(dataset1, ..., layer_name = "dataset1")
map.add_circle_markers_from_xy(dataset2, ..., layer_name = "dataset2")
```

Thank you for your efforts! This library has huge potential, I'm excited to dig deeper.

**Comment by lopezvoliver** [comment]
This issue has been solved in ipyleaflet by adding `visible` and `opacity` to vector tile layer:

![leafmap_opacity_visible](https://github.com/opengeos/leafmap/assets/14804652/62d4b32b-2785-40a4-b0de-fff6003b77f1)

@zvezdi the issue with circle markers is also an issue upstream, but I think this will be need to be solved further upstream (in leaflet.js) because circleMarkers do not have the `setOpacity` method, as demonstrated in this [jsfiddle](https://jsfiddle.net/lopezvoliver/92b04761/54/).

**Comment by giswqs** [comment]
@lopezvoliver Thank you very much for fixing this issue upstream. This is great!
