### ISSUE TITLE
leafmap on deepnote causes exception: "field() got an unexpected keyword argument 'alias'"

### ISSUE THREAD

**Issue by nrchtct** [opengeos/leafmap#751]
### Environment Information

- [deepnote notebook ](https://deepnote.com/app/uclab_potsdam/leafmap-test-b970f216-68cd-4a93-932c-c61747b4a580)
- Python 3.9

### Description

I am trying to work with leafmap in Jupyter Notebooks on Deepnote.com and I am having trouble getting leafmap to be properly imported. 

### What I Did

```
!pip install leafmap
import leafmap
```

Without getting to any mapping fun, the output is the following:

`Exception: field() got an unexpected keyword argument 'alias'`

Any pointers or suggestions are appreciated. Thank you!

**Comment by giswqs** [comment]
I am not familar with deepnote, but I noticed some errors at the end of the installation. That's probably related to the restricted environment on deepnote.
![image](https://github.com/opengeos/leafmap/assets/5016453/ea85ffbb-2c15-4f01-b3b4-0e5b0fc1abaf)

I tested it on Google Colab, and it works fine. 
![image](https://github.com/opengeos/leafmap/assets/5016453/5525e791-22ae-4559-af1d-df0315608278)

**Comment by nrchtct** [comment]
thank you! yes, it is working on colab just fine - i am trying to get it work on deepnote. probably has something to do with attrs & jsonschema…

**Comment by giswqs** [comment]
It seems ipywidget is not well supported no deepnote. It can't render ipyleaflet maps. The issue needs to be resolved by deepnote. Closing this issue for now. 

![](https://i.imgur.com/n3QabzQ.png)

Relevant issues:
- https://community.deepnote.com/c/ask-anything/ipywidgets
- https://community.deepnote.com/c/ask-anything/when-will-ipywidgets-support-be-added
