### ISSUE TITLE
Panel Leafmap: Error: Could not process update msg for model id

### ISSUE THREAD

**Issue by MarcSkovMadsen** [opengeos/leafmap#752]
I'm trying to get [leafmap](https://github.com/opengeos/leafmap) working with Panel similarly to [Solara-Leafmap](https://github.com/opengeos/solara-geospatial/blob/main/pages/01_leafmap.py).

A lot of features work. But when I click the tool icon nothing visible happens. But in the console the error below is logged.

```bash
Error: Could not process update msg for model id: d5ea3f69eff947928f88b58f36d3ceaa
    at ipywidgets_bokeh.js?v=562368b20a64be95651bb8246b7420f7fce55538dff999aefaa78662a14d0d39:8:1474147
    at async _._handleCommMsg (ipywidgets_bokeh.js?v=562368b20a64be95651bb8246b7420f7fce55538dff999aefaa78662a14d0d39:2:623644)
    at async _._handleMessage (ipywidgets_bokeh.js?v=562368b20a64be95651bb8246b7420f7fce55538dff999aefaa78662a14d0d39:2:625144)
```

![image](https://github.com/bokeh/ipywidgets_bokeh/assets/42288570/2bc0934a-7b12-4097-8a6d-6bc159d77a53)

```python
import leafmap

import panel as pn

pn.extension("ipywidgets")

widget = leafmap.Map()

layout = pn.Column(
    widget,
).servable()
```

You can see how it should work [here](https://giswqs-solara-geospatial.hf.space/leafmap)

![image](https://github.com/bokeh/ipywidgets_bokeh/assets/42288570/aa9c9e66-019d-43be-b8ce-ecca6b061f44)

I don't know if this issue is caused by `ipywidgets_bokeh` or by `leafmap`. Thus I have crossposted in [ipywidgets_bokeh #106](https://github.com/bokeh/ipywidgets_bokeh/issues/106)

```bash
Name: bokeh
Version: 3.4.1
Location: /home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages
Requires: contourpy, jinja2, numpy, packaging, pandas, pillow, pyyaml, tornado, xyzservices
Required-by: ipywidgets-bokeh, panel
---
Name: ipywidgets-bokeh
Version: 1.6.0
Location: /home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages
Requires: bokeh, ipykernel, ipywidgets
Required-by:
---
Name: leafmap
Version: 0.33.0
Location: /home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages
Requires: bqplot, colour, duckdb, folium, gdown, geojson, ipyevents, ipyfilechooser, ipyleaflet, ipywidgets, matplotlib, numpy, pandas, plotly, pyshp, pystac-client, python-box, scooby, whiteboxgui, xyzservices
Required-by:
---
Name: panel
Version: 1.5.0a3.post1.dev124+g5b59d248.d20240606
Location: /home/jovyan/repos/private/panel/.venv/lib/python3.11/site-packages
Editable project location: /home/jovyan/repos/private/panel
Requires: bleach, bokeh, linkify-it-py, markdown, markdown-it-py, mdit-py-plugins, packaging, pandas, param, pyviz-comms, requests, tqdm, typing-extensions
Required-by:
```

**Comment by giswqs** [comment]
This seems an issue with `ipywidgets_bokeh`. Can you try using `ipywidgets_bokeh` directly with Panel without leafmap? If it doesn't work either, then it is an `ipywidgets_bokeh` issue. Otherwise, it may be a leafmap issue.

**Comment by giswqs** [comment]
This does not seem to be issue unique to leafmap. I tried ipyleaflet, it does not work either. 

```python
import ipyleaflet

import panel as pn

pn.extension("ipywidgets")

widget = ipyleaflet.Map()

layout = pn.Column(
    widget,
).servable()
```
![image](https://github.com/opengeos/leafmap/assets/5016453/7d79f97b-df48-4b80-9a65-5ce949b2d1b3)

**Comment by giswqs** [comment]
Since this is an upstream issue with ipyleaflet and ipywidgets_bokeh, closing this issue for now.
