### ISSUE TITLE
basemaps do not work with pydeck engine

### ISSUE THREAD

**Issue by cboettig** [opengeos/leafmap#753]
### Environment Information

-   leafmap version: 0.32.1
-   Python version: 3.10.12
-   Operating System: Linux (ubuntu 22.04)

### Description

Basemaps do not seem to work with the pydeck engine.  (I think this is visible in the example shown in the documentation, which displays an error message now) https://leafmap.org/notebooks/29_pydeck/

related - it appears there is no `add_basemap()` method for the `lonboard` based pydeck version.  

### What I Did

as in the tutorial,  https://leafmap.org/notebooks/29_pydeck/

**Comment by giswqs** [comment]
This issue has been fixed in #757. 

lonboard needs to support xyz tile layer before leafmap can supports the `add_basemap()` function.  See https://github.com/developmentseed/lonboard/discussions/201
