### ISSUE TITLE
Error adding basemap to Lonboard Map

### ISSUE THREAD

**Issue by spatialthoughts** [opengeos/leafmap#798]
### Environment Information

-   leafmap version: 0.35
-   Python version: 3.10
-   Operating System: Colab (Ubuntu)

### Description

```
import leafmap.deckgl as leafmap
from lonboard import basemap

m = leafmap.Map(height=600, basemap_style=basemap.CartoBasemap.DarkMatterNoLabels)
m
```

This results in an error *TypeError: ViewState.__new__() got an unexpected keyword argument 'basemap_style'*. 

Diving into the code, this seems to be because the kwargs are passed on to view_state and not lonboard.Map

```
        super().__init__(
            _height=height,
            show_tooltip=show_tooltip,
            layers=layers,
            view_state=kwargs,
        )
```

**Comment by giswqs** [comment]
Try this:

```python
import leafmap.deckgl as leafmap
from lonboard import basemap

m = leafmap.Map(height=600)
m.add_basemap("CartoDB.DarkMatterNoLabels")
m
```

**Comment by spatialthoughts** [comment]
This gives *AttributeError: 'Map' object has no attribute 'add_basemap'* error

Reproducible example on Colab
https://colab.research.google.com/drive/1TEG2_7WEUwkcfoKb4zxx2NE5P8OYdfuz?usp=sharing

**Comment by giswqs** [comment]
Thank you for report. It has been fixed in #799. Please update it to v0.35.1

```python
import leafmap.deckgl as leafmap
from lonboard import basemap

m = leafmap.Map(height=600, basemap_style=basemap.CartoBasemap.DarkMatterNoLabels)
m
```
![image](https://github.com/opengeos/leafmap/assets/5016453/5ee6ef83-c808-441e-a7f3-3bb45bcb2e96)

**Comment by spatialthoughts** [comment]
Incredible! Less than 2 hours from bug report to fix to release. Upgraded and uses it to create the visualization I was after.

<img width="823" alt="lonboard_rivers" src="https://github.com/opengeos/leafmap/assets/5227506/dee8f096-9672-4d95-8e93-fdfd2e063e41">

**Comment by giswqs** [comment]
My pleasure. That was an easy fix. I should improve the lonboard module when I have time. There is still a lot of room for improvement.
