### ISSUE TITLE
Reorder layers interactively

### ISSUE THREAD

**Issue by karantai** [opengeos/leafmap#916]
From my perspective, it would be highly beneficial to have the ability to reorder raster layers interactively. In my case, I often visualize multiple raster layers on a map but don’t always know the ideal layer order beforehand. Being able to adjust the layer arrangement on the fly would provide valuable insights. For example, plotting tiles that contain houses on top of a larger background image would be much easier with this interactive functionality.

What is you opinion on that matter?

Thank you in advance.

**Comment by giswqs** [comment]
Yes, it would be a nice feature to add. Unfortunately, this is challenging to implement. There are no existing ipywidgets that support drag-and-drop or reorder components. 
https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html
