### ISSUE TITLE
maplibre points demo (adding text from geojson) not working

### ISSUE THREAD

**Issue by cboettig** [opengeos/leafmap#936]
Running the code in https://leafmap.org/maplibre/geojson_points/ generates a blank map, as seen at https://maps.gishub.org/maplibre/geojson_points.html .  

![image](https://github.com/user-attachments/assets/cb238a77-7f91-481a-b004-42b111244350)

It should generate a map with image symbols and date text added, as seen in the libremap example it links to: https://maplibre.org/maplibre-gl-js/docs/examples/geojson-markers

![image](https://github.com/user-attachments/assets/6f78c6d1-af4a-4d22-9814-496fceb77bc9)

**Comment by giswqs** [comment]
It used to work. Not sure why it stops working. Try this one: https://leafmap.org/maplibre/add_image/

**Comment by cboettig** [comment]
@giswqs thanks!  Wow so this is weird, apparently it is just the `style="positron"` that is breaking it.  The above example works with the default basemap, and the kitty example breaks in the same way if you use `style="positron"`....

**Comment by giswqs** [comment]
Intersting! There are two positron basemaps, one from cartodb and the other one from [OpenFreeMap]( https://openfreemap.org). 

The default `positron' uses OpenFreeMap, while `carto-positrion` uses CartoDB, which used to be the default one. 

It appears that the OpenFreeMap basemaps (e.g., liberty, positron, and bright) are breaking this particular example. Not sure why. 

I am going to switch the default `positron` to use CartoDB.

**Comment by giswqs** [comment]
@cboettig I just released v0.38.10 that fixes this issue. Thank you for the hints. Otherwise, this werid bug might take me hours to debug.
