### ISSUE TITLE
Unable to edit polygon metadata

### ISSUE THREAD

**Issue by robmarkcole** [opengeos/leafmap#945]
The gif on https://leafmap.org/notebooks/45_create_vector/ shows editing the metadata. However I cannot access this functionality, and possible the UI has changed as I don't see the spanner icon? 

<img width="1441" alt="image" src="https://github.com/user-attachments/assets/3e3a6952-a04b-4fbf-80b8-138ba2c4d883">

Note: I am interested in demonstrating an 'annotation' capability using this tool

**Comment by robmarkcole** [comment]
Running on colab, I DO see the spanner. Perhaps this is a bug or issue related to the env. This is running in a notebook in vscode on lightning.ai

**Comment by giswqs** [comment]
This is probably an issue with the env on lightning.ai. ipyleaflet and ipywidgets may not well on some custom Jupyter environment as the JS part of the library may be missing.

**Comment by robmarkcole** [comment]
Thanks again!
