### ISSUE TITLE
Gradio app blank

### ISSUE THREAD

**Issue by robmarkcole** [opengeos/leafmap#947]
### Environment Information

MacOS & vscode & chrome

### Description

Run the [demo app](https://leafmap.org/notebooks/66_gradio/)

### What I Did
Doesn't display:
<img width="1389" alt="image" src="https://github.com/user-attachments/assets/30b0e605-3404-427c-bf6d-1a6945188d97">

**Comment by giswqs** [comment]
I have not used gradio for a long time. Need to look into it

**Comment by giswqs** [comment]
Gradio does not have good support for folium. It appears that their `gradio-folium` package is no longer functioning. I don't think I will invest time to further develop this. I recommend using solara instead, which has native support for ipyleaflet. See examples [here](https://github.com/opengeos/solara-geospatial). 

https://github.com/gradio-app/gradio/issues/3190#issuecomment-1781778216

```bash
pip install gradio-folium
```

```python
import gradio as gr
from gradio_folium import Folium
from folium import Map

with gr.Blocks() as demo:
    map = Folium(value=Map(location=[25.7617, -80.1918]), height=400)

demo.launch()
```
