### ISSUE TITLE
leafmap.create_timelapse returns No images found in the input directory.

### ISSUE THREAD

**Issue by robmarkcole** [opengeos/leafmap#948]
In https://leafmap.org/notebooks/72_timelapse/ I get `No images found in the input directory.` which was reported in https://github.com/opengeos/leafmap/issues/411

**Comment by robmarkcole** [comment]
Are you mac or windows?

**Comment by giswqs** [comment]
I am using Linux. So the error occurs on macOS?

**Comment by giswqs** [comment]
I just tested on mac. Working fine as well.

**Comment by robmarkcole** [comment]
Very strange.. Might be a hidden file, something to do with my path, not sure... 

<img width="843" alt="image" src="https://github.com/user-attachments/assets/f40c228d-adb0-43ff-8fe9-a1a4cdee45b7">

**Comment by giswqs** [comment]
It might because you are using venv. The working directory file path is different. Try setting `images = /fullpath_to_dir/*.tif`
