### ISSUE TITLE
'Map' object has no attribute 'edit_points'

### ISSUE THREAD

**Issue by robmarkcole** [opengeos/leafmap#950]
In https://leafmap.org/notebooks/95_edit_vector/ I get error
```
AttributeError: 'Map' object has no attribute 'edit_points'
```
- leafmap==0.35.11
- vscode

**Comment by robmarkcole** [comment]
No issues on colab, seems to be related to the env

**Comment by giswqs** [comment]
Your leafmap version is outdated. This function was added recently. You need to update leafmap to use it

**Comment by robmarkcole** [comment]
Interesting, it was a fresh install from pypi an hour ago. One of the following must have downgraded it..
```
lonboard==0.3.0
numpy<2
rioxarray
xarray
rasterio
```

**Comment by giswqs** [comment]
Try removing lonboard and numpy version pin

**Comment by robmarkcole** [comment]
Uninstalled lonboard, now have `leafmap==0.38.12` and no issue. So it was the lonboard pin from [84_read_parquet.ipynb](https://github.com/opengeos/leafmap/blob/7d9269530416fcb73b9e88608f54a6613a70b5d1/docs/notebooks/84_read_parquet.ipynb#L24)
