### ISSUE TITLE
Maplibre-based streamlit maps do not render in Safari

### ISSUE THREAD

**Issue by cassiebuhler** [opengeos/leafmap#965]
### Environment Information

-   leafmap version: 0.38.12 
-   Python version: 3.12.7
-   Operating System: macOS Sonoma 14.7.1 

### Description

I am trying to make streamlit apps that display maps with leafmap.maplibregl. However, I've found that maps on streamlit apps with the maplibre backend don’t appear when they’re opened on Safari on macOS desktop (which also means it can't appear on iPhone browsers).

Please refer to this app for an example:
https://huggingface.co/spaces/giswqs/streamlit-maplibre

It seems to just be a maplibregl module issue, as I’ve tested out leafmap.foliumap (https://huggingface.co/spaces/boettiger-lab/tpl) which showed up just fine in Safari.

### What I Did

Clicking the link to view the app. It shows a blank window where the map should display. The image below is a screenshot of the issue:

<img width="1499" alt="maplibregl-safari" src="https://github.com/user-attachments/assets/9cc604d4-d530-47aa-81ce-db86c5946bc4">

**Comment by giswqs** [comment]
Can you try out this to see if it works with Safari? I am not sure if this is a leafmap or maplibre issue.
https://eoda-dev.github.io/py-maplibregl/streamlit/

**Comment by cassiebuhler** [comment]
Thanks for looking into this. I cloned your repo and it still isn’t showing up in Safari. I also tried the example you linked and had the same result. 

For reference, I’m using Safari 18.1, streamlit 1.35.0, maplibre 0.2.6, and geopandas 1.0.1. 

<img width="1025" alt="sfparking" src="https://github.com/user-attachments/assets/c1dccc1f-395b-4a99-a7b2-eddf8a92d04e">
<img width="1010" alt="maplibre-ex" src="https://github.com/user-attachments/assets/4156f831-7bb1-4a76-9637-d29922ed1165">

**Comment by giswqs** [comment]
I meant cloning the repo and run it locally, not on Hugging Face

**Comment by cboettig** [comment]
@giswqs thanks , note the above examples are already a local jupyterhub, no huggingface involved.

**Comment by giswqs** [comment]
This is probably an upstream issue as the SF Bike Parking example is from the maplibre package. Leafmap is not used in this example. 

https://eoda-dev.github.io/py-maplibregl/streamlit/

**Comment by cboettig** [comment]
@giswqs thanks, we'll test with that.  yeah looks like this is probably upstream of leafmap.  Appreciate you testing. 

Will have to figure out why your local safari works but ours does not.  Just to be clear, you also see safari not able to render in huggingface, but for you safari works locally?  can you share your safari version?  

(sorry Cassie has Safari but I just have a ubuntu box here)

**Comment by giswqs** [comment]
Correct. Safari can render the streamlit-maplibre app running locally, but it gets a black screen when rendering the same app on Hugging Face.

**Comment by giswqs** [comment]
Closing this issue as it is an upstream issue. Hope it will be resolved upstream soon.
