### ISSUE TITLE
Did you drop leafmap.connect_postgis??

### ISSUE THREAD

**Issue by glemoine62** [opengeos/leafmap#989]
### Environment Information

-   leafmap version: 0.40.1
-   Python version: 3.12.3
-   Operating System: Ubuntu 24.04.1

### Description

I did a fresh install of leafmap this morning and discovered that leafmap.connect_postgis is no longer working. Did you drop it?
I see that there is now common.read_postgis (instead?).

### What I Did

```
python3 -c 'import leafmap; print(dir(leafmap))' | grep connect_postgis
```
(returns nothing)

**Comment by glemoine62** [comment]
Aha, now leafmap.common.connect_postgis().

**Comment by giswqs** [comment]
Correct. The * import of the common module has been remvoed. See https://github.com/opengeos/leafmap/pull/980
You can use `from leafmap.common import connect_postgis`
